### ISSUE TITLE
ses6: "cluster does not have a DNS domain configured" error in Stage 2 orchestration step parsing phase

### ISSUE THREAD

**Issue by jan--f** [SUSE/sesdev#181]
Using this create command:
`sesdev create ses6 --libvirt-networks routed_all --domain virt1.home.fajerski.name --roles "[master, mon, mgr], [storage, mon, mgr],[storage,mon.mgr],[storage, mds],[storage,mds]" --os sles-15-sp1 --libvirt-storage-pool sesdev-nvme --num-disks 2 --ram 4 ses`

I end up with a cluster where the minion ids are `master`, `node1` and so on. This interferes with deepsea deployments, eg:
```
 master: ***** RUNNING stage.2 *******
    master: ++ echo ''
    master: ++ echo '***** RUNNING stage.2 *******'
    master: ++ deepsea stage run --simple-output ceph.stage.2
    master: Starting orchestration: ceph.stage.2
    master: Parsing orchestration ceph.stage.2 steps... 
    master: fail
    master: 
    master: An error occurred when rendering one of the following states:
    master:     - ceph.ssl (/srv/salt/ceph/ssl)
    master: Error description:
    master:   - Rendering SLS 'base:ceph.ssl.default' failed: Jinja error: According to the 'domain' grain, the cluster does not have a DNS domain configured
    master:     Traceback (most recent call last):
    master:       File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 392, in render_jinja_tmpl
    master:         output = template.render(**decoded_context)
    master:       File "/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    master:         return original_render(self, *args, **kwargs)
    master:       File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    master:         return self.environment.handle_exception(exc_info, True)
    master:       File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    master:         reraise(exc_type, exc_value, tb)
    master:       File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    master:         raise value.with_traceback(tb)
    master:       File "<template>", line 1, in top-level template code
    master:       File "/var/cache/salt/minion/extmods/modules/deepsea.py", line 97, in ssl_cert_cn_wildcard
    master:         raise Exception("According to the 'domain' grain, the cluster does"
    master:     Exception: According to the 'domain' grain, the cluster does not have a DNS domain configured
    master:     
    master:     ; line 1
    master:     
    master:     ---
    master:     {% set CN = salt['deepsea.ssl_cert_cn_wildcard']() %}    <======================
    master:     
    master:     create CA:
    master:       module.run:
    master:         - name: tls.create_ca
    master:         - ca_name: deepsea
    master:     [...]
    master:     ---
Command '['vagrant', 'up']' failed: ret=1 stderr:
```

THis used to work no problem, I haven't checked for a root cause yet.

**Comment by smithfarm** [comment]
I can't reproduce this. Could it be that it's caused by the syntax error in the roles string?

```
--roles "[master, mon, mgr], [storage, mon, mgr],[storage,mon.mgr],[storage, mds],[storage,mds]"
```

should be "mon, mgr" instead of "mon.mgr".

**Comment by smithfarm** [comment]
```
$ sesdev create ses6 --roles "[master, mon, mgr], [storage, mon, mgr], [storage, mon, mgr], [storage, mds], [storage, mds]" --os sles-15-sp1 --num-disks 2 --ram 4 ses6
...
...
...
    master: Finished stage ceph.stage.4: succeeded=3/3 failed=0/3
    master: ++ sleep 5
    master: deployment complete!
    master: ++ echo 'deployment complete!'
=== Deployment Finished ===
```

Just out of curiosity, what does `sesdev --version` say?

**Comment by jan--f** [comment]
> ```
> $ sesdev create ses6 --roles "[master, mon, mgr], [storage, mon, mgr], [storage, mon, mgr], [storage, mds], [storage, mds]" --os sles-15-sp1 --num-disks 2 --ram 4 ses6
> ```

I run this with --domain. Maybe that's an issue? Will try without.

> 
> Just out of curiosity, what does `sesdev --version` say?

```
 % sesdev --version                                                                                                                                                                            
sesdev 1.1.8

**Comment by jan--f** [comment]
> should be "mon, mgr" instead of "mon.mgr"?

Good catch, didn't fix this issue but another mystery solved.

**Comment by smithfarm** [comment]
> I run this with --domain. Maybe that's an issue? Will try without.

I have never tested `--domain`. It could very well be broken.

**Comment by jan--f** [comment]
It worked until recently. Also not using `--domain` ends up in the same place. No hostname is set explicitly, so salt uses the short hostname as the minion_id.

**Comment by smithfarm** [comment]
Your OS?

**Comment by jan--f** [comment]
Archlinux but that shouldn't impact how my VMs are configured. bisecting the lattest commits led me to a6d4fd8e7e1e1d191c78cd5f198618b102ae8735 as the culprit. will look further whats going on.

**Comment by smithfarm** [comment]
This is just a hunch, but perhaps you are using a different vagrant than I am, or your vagrant has a different set of plugins.

```
$ zypper se -s vagrant | grep '^i'
i  | ruby2.5-rubygem-vagrant_cloud             | package    | 2.0.3-lp151.10.1            | x86_64 | Devel project for Vagrant (openSUSE_Leap_15.1)
i+ | vagrant                                   | package    | 2.2.7-lp151.3.4             | x86_64 | Devel project for Vagrant (openSUSE_Leap_15.1)
i  | vagrant-bash-completion                   | package    | 2.2.7-lp151.3.4             | noarch | Devel project for Vagrant (openSUSE_Leap_15.1)
i+ | vagrant-libvirt                           | package    | 0.0.45-lp151.17.12          | x86_64 | Devel project for Vagrant (openSUSE_Leap_15.1)
i  | vagrant-vim                               | package    | 2.2.7-lp151.3.4             | noarch | Devel project for Vagrant (openSUSE_Leap_15.1)
```

**Comment by smithfarm** [comment]
I do remember that older versions of vagrant did not add the line to `/etc/hosts`...
