### ISSUE TITLE
bootstrap.sh sometimes defaults to Python 2

### ISSUE THREAD

**Issue by smithfarm** [SUSE/sesdev#194]
I got a report from a user on openSUSE Leap 15.1 that `./bootstrap.sh` gave him the following error:

```
New python executable in /home/alex/Documents/Work/MyLab/sesdev/venv/bin/python2
Also creating executable in /home/alex/Documents/Work/MyLab/sesdev/venv/bin/python
Installing setuptools, pip, wheel...
done.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Obtaining file:///home/alex/Documents/Work/MyLab/sesdev
ERROR: Command errored out with exit status 1:
command: /home/alex/Documents/Work/MyLab/sesdev/venv/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/alex/Documents/Work/MyLab/sesdev/setup.py'"'"'; file='"'"'/home/alex/Documents/Work/MyLab/sesdev/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' egg_info
cwd: /home/alex/Documents/Work/MyLab/sesdev/
Complete output (7 lines):
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/home/alex/Documents/Work/MyLab/sesdev/setup.py", line 20, in <module>
version=get_version_from_spec(),
File "/home/alex/Documents/Work/MyLab/sesdev/setup.py", line 16, in get_version_from_spec
return ver_match[1]
TypeError: '_sre.SRE_Match' object has no attribute '__getitem__'
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I'm not sure why virtualenv would default to Python 2 - maybe it's an old version of virtualenv - but bootstrap.sh should be able to deal with it.

**Comment by toabctl** [comment]
> I'm not sure why virtualenv would default to Python 2 - maybe it's an old version of virtualenv - but bootstrap.sh should be able to deal with it.

If you have both (python2-virtualenv and python3-virtualenv) installed, you can configure what `/usr/bin/virtualenv` is (via `update-alternatives`).

```
$ ls -al /usr/bin/virtualenv
lrwxrwxrwx 1 root root 28 Mär  9 03:17 /usr/bin/virtualenv -> /etc/alternatives/virtualenv
$ ls -al /etc/alternatives/virtualenv
lrwxrwxrwx 1 root root 23 Mär 15 16:31 /etc/alternatives/virtualenv -> /usr/bin/virtualenv-3.8
```
