### ISSUE TITLE
ses7 deployment fails with: AttributeError: 'NoneType' object has no attribute 'startswith' for self.settings.ceph_salt_git_branch

### ISSUE THREAD

**Issue by toabctl** [SUSE/sesdev#216]
On TW, with git commit 022cedfef463ef3f7ea6d7fa9bccc62385b00de5

```
$ sesdev create ses7 --single-node ses7-mini
Traceback (most recent call last):
  File "/home/tom/devel/suse/sesdev/venv/bin/sesdev", line 11, in <module>
    load_entry_point('sesdev', 'console_scripts', 'sesdev')()
  File "/home/tom/devel/suse/sesdev/sesdev/__init__.py", line 17, in sesdev_main
    cli(prog_name='sesdev')
  File "/home/tom/devel/suse/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/tom/devel/suse/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/tom/devel/suse/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tom/devel/suse/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tom/devel/suse/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tom/devel/suse/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/tom/devel/suse/sesdev/sesdev/__init__.py", line 660, in ses7
    _create_command(deployment_id, deploy, settings_dict)
  File "/home/tom/devel/suse/sesdev/sesdev/__init__.py", line 576, in _create_command
    dep = seslib.Deployment.create(deployment_id, settings)
  File "/home/tom/devel/suse/sesdev/seslib/__init__.py", line 1590, in create
    dep.save()
  File "/home/tom/devel/suse/sesdev/seslib/__init__.py", line 1163, in save
    scripts = self.generate_vagrantfile()
  File "/home/tom/devel/suse/sesdev/seslib/__init__.py", line 1082, in generate_vagrantfile
    if self.settings.ceph_salt_git_branch.startswith('origin/pr/'):
AttributeError: 'NoneType' object has no attribute 'startswith'

```

**Comment by smithfarm** [comment]
Thanks, trying to reproduce it now.

**Comment by smithfarm** [comment]
It's related to #210 which I merged without sufficient testing - will try to do better next time :-)

**Comment by toabctl** [comment]
well - we need better test coverage I guess....

**Comment by smithfarm** [comment]
> well - we need better test coverage I guess....

Yes, I plan to handwrite a bash script for this :-P :-P :-P

**Comment by smithfarm** [comment]
In all seriousness, now - while regressions in master are always regrettable, I think anyone following master closely must be prepared to accept that they *will* happen.

Regressions in released versions would be something serious that should definitely be avoided at all costs.

**Comment by smithfarm** [comment]
I opened two PRs, both of which fix this.

The first PR, #217, is a wider cleanup to avoid falling into this `AttributeError: 'NoneType' object has no attribute 'startswith'` trap in the future by simply making str-type settings default to the empty string instead of None.

The second one, #218, is a minimal patch to fix this particular instance of `AttributeError: 'NoneType' object has no attribute 'startswith'`

**Comment by toabctl** [comment]
> Yes, I plan to handwrite a bash script for this :-P :-P :-P

heh
