### ISSUE TITLE
Failed to install a single-node `octopus` cluster

### ISSUE THREAD

**Issue by votdev** [SUSE/sesdev#233]
Running `sesdev create octopus --single-node octopus` results in the following failure:
```
    master: .
    master: .
    master: .
    master: done]
    master: (12/12) Installing: ceph-salt-15.2.0+1585928278.gce48e3b-lp152.2.1.noarch [.
    master: .
    master: .
    master: .
    master: .
    master: .
    master: .
    master: .
    master: .
    master: .
    master: .
    master: .
    master: done]
    master: ++ systemctl restart salt-master
    master: ++ set +ex
    master: ++ sleep 5
    master: ++ set +x
    master: +++ salt '*' test.ping
    master: +++ grep True
    master: +++ wc --lines
    master: ++ MINIONS_RESPONDING=1
    master: ++ '[' 1 = 1 ']'
    master: ++ break
    master: ++ set -ex
    master: ++ salt '*' saltutil.pillar_refresh
    master: master.octopus.com:
    master:     True
    master: ++ salt '*' saltutil.sync_all
    master: master.octopus.com:
    master:     ----------
    master:     beacons:
    master:     clouds:
    master:     engines:
    master:     grains:
    master:     log_handlers:
    master:     matchers:
    master:     modules:
    master:         - modules.ceph_orch
    master:         - modules.ceph_salt
    master:     output:
    master:     proxymodules:
    master:     renderers:
    master:     returners:
    master:     sdb:
    master:     serializers:
    master:     states:
    master:         - states.ceph_salt
    master:     thorium:
    master:     utils:
    master: ++ sleep 2
    master: PATH is /usr/sbin:/usr/bin:/sbin:/bin
    master: ceph-salt is /usr/bin/ceph-salt
    master: ++ echo 'PATH is /usr/sbin:/usr/bin:/sbin:/bin'
    master: ++ type ceph-salt
    master: ++ MON_NODES_COMMA_SEPARATED_LIST=
    master: ++ MGR_NODES_COMMA_SEPARATED_LIST=
    master: ++ ceph-salt config /ceph_cluster/minions add master.octopus.com
    master: Warning: Could not load preferences file /root/.ceph_salt_config_shell/prefs.bin.
    master: Traceback (most recent call last):
    master:   File "/usr/lib/python3.6/site-packages/configshell_fb/shell.py", line 806, in _execute_command
    master:     target = self._current_node.get_node(path)
    master:   File "/usr/lib/python3.6/site-packages/configshell_fb/node.py", line 1854, in get_node
    master:     return next_node.get_node(next_path)
    master:   File "/usr/lib/python3.6/site-packages/configshell_fb/node.py", line 1861, in get_node
    master:     next_node = adjacent_node(next_node_name)
    master:   File "/usr/lib/python3.6/site-packages/configshell_fb/node.py", line 1827, in adjacent_node
    master:     return self.get_child(name)
    master:   File "/usr/lib/python3.6/site-packages/configshell_fb/node.py", line 1796, in get_child
    master:     % (self.path.rstrip('/'), name))
    master: ValueError: No such path /ceph_cluster
    master: 
    master: During handling of the above exception, another exception occurred:
    master: 
    master: Traceback (most recent call last):
    master:   File "/usr/bin/ceph-salt", line 11, in <module>
    master:     load_entry_point('ceph-salt==15.2.0+1585928278.gce48e3b', 'console_scripts', 'ceph-salt')()
    master:   File "/usr/lib/python3.6/site-packages/ceph_salt/__init__.py", line 55, in ceph_salt_main
    master:     cli(prog_name='ceph-salt')
    master:   File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    master:     return self.main(*args, **kwargs)
    master:   File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    master:     rv = self.invoke(ctx)
    master:   File "/usr/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    master:     return _process_result(sub_ctx.command.invoke(sub_ctx))
    master:   File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    master:     return ctx.invoke(self.callback, **ctx.params)
    master:   File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    master:     return callback(*args, **kwargs)
    master:   File "/usr/lib/python3.6/site-packages/ceph_salt/__init__.py", line 82, in config_shell
    master:     if not run_config_cmdline(" ".join(config_args)):
    master:   File "/usr/lib/python3.6/site-packages/ceph_salt/config_shell.py", line 1012, in run_config_cmdline
    master:     shell.run_cmdline(cmdline)
    master:   File "/usr/lib/python3.6/site-packages/configshell_fb/shell.py", line 843, in run_cmdline
    master:     self._execute_command(path, command, pparams, kparams)
    master:   File "/usr/lib/python3.6/site-packages/configshell_fb/shell.py", line 808, in _execute_command
    master:     raise ExecutionError(str(msg))
    master: configshell_fb.node.ExecutionError: No such path /ceph_cluster
Command '['vagrant', 'up']' failed: ret=1 stderr:
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by smithfarm** [comment]
This isn't really a bug. If you are installing sesdev from source, it makes sense to also install ceph-salt from source.

Please try:

```
sesdev create octopus --ceph-salt-branch master --single-node octopus
```

The problem will go away once a new ceph-salt release is cut.
