### ISSUE TITLE
ses5: igw transiently fails to start

### ISSUE THREAD

**Issue by smithfarm** [SUSE/sesdev#239]
Reproducer:

    sesdev create ses5 ses5

The error doesn't happen every time. When it does happen, `systemctl reload lrbd.service` fails on the second igw node. The reason it fails the lrbd.service is inactive. The reason it's inactive is:

```
node2:~ # systemctl status --lines=40 lrbd.service
● lrbd.service - configures target.service from Ceph
   Loaded: loaded (/usr/lib/systemd/system/lrbd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2020-04-10 06:49:16 UTC; 7min ago
 Main PID: 20914 (code=exited, status=1/FAILURE)

Apr 10 06:49:15 node2 systemd[1]: Starting configures target.service from Ceph...
Apr 10 06:49:16 node2 lrbd[20914]: ERROR: list index out of range
Apr 10 06:49:16 node2 lrbd[20914]: rbd -p iscsi-images --name client.igw.node2 map demo
Apr 10 06:49:16 node2 lrbd[20914]: /dev/rbd0
Apr 10 06:49:16 node2 lrbd[20914]: targetcli /backstores/rbd create name=iscsi-images-demo dev=/dev/rbd/iscsi-images/demo
Apr 10 06:49:16 node2 lrbd[20914]: targetcli exit
Apr 10 06:49:16 node2 lrbd[20914]: Warning: Could not load preferences file /root/.targetcli/prefs.bin.
Apr 10 06:49:16 node2 lrbd[20914]: mount: none is already mounted or /sys/kernel/config busy
Apr 10 06:49:16 node2 lrbd[20914]: targetcli 2.1-suse (rtslib 2.2-sle12)
Apr 10 06:49:16 node2 lrbd[20914]: Copyright (c) 2011-2014 by Datera, Inc.
Apr 10 06:49:16 node2 lrbd[20914]: All rights reserved.
Apr 10 06:49:16 node2 lrbd[20914]: /> Traceback (most recent call last):
Apr 10 06:49:16 node2 lrbd[20914]:   File "/usr/lib/python2.7/site-packages/configshell/shell.py", line 990, in run_interactive
Apr 10 06:49:16 node2 lrbd[20914]:     self._cli_loop()
Apr 10 06:49:16 node2 lrbd[20914]:   File "/usr/lib/python2.7/site-packages/configshell/shell.py", line 820, in _cli_loop
Apr 10 06:49:16 node2 lrbd[20914]:     self.run_cmdline(cmdline)
Apr 10 06:49:16 node2 lrbd[20914]:   File "/usr/lib/python2.7/site-packages/configshell/shell.py", line 934, in run_cmdline
Apr 10 06:49:16 node2 lrbd[20914]:     self._execute_command(path, command, pparams, kparams)
Apr 10 06:49:16 node2 lrbd[20914]:   File "/usr/lib/python2.7/site-packages/configshell/shell.py", line 899, in _execute_command
Apr 10 06:49:16 node2 lrbd[20914]:     self.log.error(msg)
Apr 10 06:49:16 node2 lrbd[20914]:   File "/usr/lib/python2.7/site-packages/configshell/log.py", line 159, in error
Apr 10 06:49:16 node2 lrbd[20914]:     self._log('error', msg)
Apr 10 06:49:16 node2 lrbd[20914]:   File "/usr/lib/python2.7/site-packages/configshell/log.py", line 112, in _log
Apr 10 06:49:16 node2 lrbd[20914]:     self.con.display(msg)
Apr 10 06:49:16 node2 lrbd[20914]:   File "/usr/lib/python2.7/site-packages/configshell/console.py", line 153, in display
Apr 10 06:49:16 node2 lrbd[20914]:     self.raw_write(text)
Apr 10 06:49:16 node2 lrbd[20914]:   File "/usr/lib/python2.7/site-packages/configshell/console.py", line 141, in raw_write
Apr 10 06:49:16 node2 lrbd[20914]:     self._stdout.write(text)
Apr 10 06:49:16 node2 lrbd[20914]: TypeError: expected a string or other character buffer object
Apr 10 06:49:16 node2 lrbd[20914]: />
Apr 10 06:49:16 node2 systemd[1]: lrbd.service: Main process exited, code=exited, status=1/FAILURE
Apr 10 06:49:16 node2 systemd[1]: Failed to start configures target.service from Ceph.
Apr 10 06:49:16 node2 systemd[1]: lrbd.service: Unit entered failed state.
Apr 10 06:49:16 node2 systemd[1]: lrbd.service: Failed with result 'exit-code'.
Apr 10 06:49:36 node2 systemd[1]: lrbd.service: Unit cannot be reloaded because it is inactive.
Apr 10 06:52:00 node2 systemd[1]: lrbd.service: Unit cannot be reloaded because it is inactive.
```

**Comment by smithfarm** [comment]
It happens even with a single "igw" role.
