### ISSUE TITLE
click 6.7: "TypeError: FOO got an unexpected keyword argument 'force'"

### ISSUE THREAD

**Issue by smithfarm** [SUSE/sesdev#266]
Latest `sesdev` installed from RPM (not reproducible on master branch installed from source):

```
$ sesdev destroy -f '*'
Traceback (most recent call last):
  File "/usr/bin/sesdev", line 11, in <module>
    load_entry_point('sesdev==1.1.10+1587124098.ga2f8189', 'console_scripts', 'sesdev')()
  File "/usr/lib/python3.6/site-packages/sesdev/__init__.py", line 20, in sesdev_main
    cli(prog_name='sesdev')
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
TypeError: destroy() got an unexpected keyword argument 'force'
```

```
$ sesdev --version
sesdev 1.1.10+1587124098.ga2f8189
```

---

```
+ sesdev create ses5 --non-interactive --roles '[master,storage,mon,mgr,mds,rgw,nfs]' --qa-test ses5-1node
Traceback (most recent call last):
  File "/usr/bin/sesdev", line 11, in <module>
    load_entry_point('sesdev==1.1.10+1587124098.ga2f8189', 'console_scripts', 'sesdev')()
  File "/usr/lib/python3.6/site-packages/sesdev/__init__.py", line 20, in sesdev_main
    cli(prog_name='sesdev')
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/sesdev/__init__.py", line 687, in ses5
    settings_dict = _gen_settings_dict('ses5', **kwargs)
TypeError: _gen_settings_dict() got an unexpected keyword argument 'force'
+ exit_status=1
```

**Comment by smithfarm** [comment]
The most frustrating thing about this bug is I don't understand why the exact same SHA1 behaves differently depending on whether it was installed from source or from RPM.

**Comment by smithfarm** [comment]
ah! Here's the difference: when installing from RPM, I get `python3-click` version 6.7-lp151.3.2, but when I install from source I get click 7.1.1

**Comment by smithfarm** [comment]
Reproduced (even when installing from source) by applying the following patch:

```
diff --git a/setup.cfg b/setup.cfg
index f782a3a..62d8bd3 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -22,7 +22,7 @@ classifier =
 
 [options]
 install_requires =
-    Click >= 6.7
+    Click >= 6.7, < 7
     Jinja2 >= 2.10.1
     libvirt-python >= 5.1.0
     pycryptodomex >= 3.4.6
```
