### ISSUE TITLE
Error removing box

### ISSUE THREAD

**Issue by ricardoasmarques** [SUSE/sesdev#507]
I'm getting the folowing error when trying to remove a box:

```
~/projects/sesdev(master) » sesdev box list                                                                                                                                                                          1 ↵ rimarques@linux-o898
List of all Vagrant Boxes installed in the system
-------------------------------------------------
leap-15.1
leap-15.2
sles-12-sp3
sles-15-sp1
(venv) -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

~/projects/sesdev(master) » sesdev box remove leap-15.2                                                                                                                                                                  rimarques@linux-o898
Traceback (most recent call last):
  File "/home/rimarques/projects/sesdev/venv/bin/sesdev", line 11, in <module>
    load_entry_point('sesdev', 'console_scripts', 'sesdev')()
  File "/home/rimarques/projects/sesdev/sesdev/__init__.py", line 41, in sesdev_main
    cli(prog_name='sesdev')
  File "/home/rimarques/projects/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/rimarques/projects/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/rimarques/projects/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rimarques/projects/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rimarques/projects/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rimarques/projects/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/rimarques/projects/sesdev/sesdev/__init__.py", line 353, in remove_box
    settings_dict = _gen_box_settings_dict(**kwargs)
TypeError: _gen_box_settings_dict() got an unexpected keyword argument 'all'
```

**Comment by smithfarm** [comment]
Thanks for reporting. I'll have a fix ready for testing very soon. Just out of curiosity, which version of Click is being used in your environment? For example, in my environment I have 7.1.2:

```
(venv) smithfarm@wilbur:~/src/ceph/smithfarm/sesdev> pip show click
Name: click
Version: 7.1.2
Summary: Composable command line interface toolkit
Home-page: https://palletsprojects.com/p/click/
Author: None
Author-email: None
License: BSD-3-Clause
Location: /home/smithfarm/src/ceph/smithfarm/sesdev/venv/lib/python3.6/site-packages
Requires: 
Required-by: sesdev
```

But some environments have Click 6 and that has different option naming semantics which we must support.

**Comment by smithfarm** [comment]
We can avoid the Click semantics issue entirely by having the command consume globs, like we did for `sesdev destroy`, et al.
