### ISSUE TITLE
sesdev upgrade breaks sesdev status/list command

### ISSUE THREAD

**Issue by jan--f** [SUSE/sesdev#536]
#531 broke the sesdev cli for me:
```
jan@ws ~/code/vagrant/sesdev (git)-[master] % g describe
v1.8.0-10-ge701c0f
jan@ws ~/code/vagrant/sesdev (git)-[master] % sesdev status
Traceback (most recent call last):
  File "/home/jan/.virtualenvs/sesdev/bin/sesdev", line 11, in <module>
    load_entry_point('sesdev', 'console_scripts', 'sesdev')()
  File "/home/jan/.virtualenvs/sesdev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/jan/.virtualenvs/sesdev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/home/jan/.virtualenvs/sesdev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/home/jan/.virtualenvs/sesdev/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/jan/code/vagrant/sesdev/sesdev/__init__.py", line 1491, in <module>
    def upgrade(deployment_id, node, devel_repos, to_version):
  File "/home/jan/.virtualenvs/sesdev/lib/python3.8/site-packages/click/decorators.py", line 170, in decorator
    _param_memo(f, OptionClass(param_decls, **attrs))
  File "/home/jan/.virtualenvs/sesdev/lib/python3.8/site-packages/click/core.py", line 1511, in __init__
    raise TypeError('Got secondary option for non boolean flag.')
TypeError: Got secondary option for non boolean flag.
1 jan@ws ~/code/vagrant/sesdev (git)-[master] % gc HEAD~2                                                                          :(
Note: switching to 'HEAD~2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 58b5d74 Merge pull request #530 from smithfarm/wip-sles-15-sp2-product-repo
jan@ws ~/code/vagrant/sesdev (git)-[master~2] % g describe
v1.8.0-6-g58b5d74
jan@ws ~/code/vagrant/sesdev (git)-[master~2] % sesdev status
Found 2 deployments:

+------+---------+---------+--------+
| ID   | Version | Status  | Nodes  |
+------+---------+---------+--------+
| ses  | ses6    | running | master |
| ses7 | ses7    | running | master |
+------+---------+---------+--------+
```
Commit 58b5d7444a70d4d2fc1e29e7d3b5ca97382f6b9b is the last that works for me.

**Comment by smithfarm** [comment]
I can't reproduce this. Could you try:

```
1. get tip of master
2. deactivate
3. ./bootstrap.sh
4. source venv/bin/activate
5. sesdev status
```

**Comment by jan--f** [comment]
Blowing away the virtualenv and recreating it (`./bootstrap.sh`) fixes this.
